#!/usr/bin/env python3
import sys
import os

# Ensure playlister_lib and spotipy are in import path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from playlister_lib.main import main
if __name__ == "__main__":
    main()
